# Generated by Django 4.1.1 on 2022-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysniffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_overloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
