# Generated by Django 4.1.1 on 2022-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysniffer', '0002_log_is_overloaded_alter_log_date_alter_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='code',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.CharField(max_length=512),
        ),
    ]
