# Generated by Django 4.1.1 on 2022-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysniffer', '0003_log_code_alter_log_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.CharField(max_length=1024),
        ),
    ]
